### ISSUE TITLE
\function()

### ISSUE THREAD

**Issue by matthewbbone** [rpruim/Lock5withR#5]
When trying to switch \function{histogram()} to \function{gf_histogram()} in the chapter 2 .rnw file, I get a series of errors:

Missing $ inserted.
Extra }, or forgotten $.
Extra }, or forgotten $.
Missing $ inserted.

This also happened in chapter 5 when replacing plotDist() with gf_dist(). 
My guess would be that \function{} was designed to only take certain functions, not those in ggformula.

**Comment by rpruim** [comment]
The problem is the underscore, which has special meaning in latex.  Let think about whether there is an easy way to fix this in the latex macro.  Else, I'll suggest an alternative (that I have used elsewhere).

**Comment by matthewbbone** [comment]
I fixed it by replacing _ with $\char`_$

**Comment by rpruim** [comment]
Let's not fix this with that sort of hack.  We don't want to type that each time we reference one of these functions.

**Comment by rpruim** [comment]
I think I have this fixed using `\detokenize{}` in the `\function{}` macro.  See 7f1ddc5ea28b1a7a5f46a434fcf513b1b2866d80
